### ISSUE TITLE
Stability in comparison to original SeqNMF (matlab code)

### ISSUE THREAD

**Issue by J-Fo-S** [ContextLab/seqnmf#10]
Hello, I am curious as to whether your lab verified the performance of this Python port with the original implementation of SeqNMF in matlab. I ask because I am experiencing very poor stability in repeated trials for some k, and I am not sure whether to assign this behavior to the SeqNMF algorithm itself or to this port. Thank you.

**Comment by jeremymanning** [comment]
Hi @J-Fo-S, this port was a very quick thing I put together...it's not debugged or tested.  I'm thrilled that it actually runs!  I tried to do as direct a port as possible (just translating MATLAB to Python line-by-line), but it's very likely that I've introduced problems.

I'm not actively developing this, but if you end up running any tests, I'd be grateful if you could post the results (either to this issue, or in a new issue).  And/or if you feel up to fixing any issues that you find, please consider submitting a pull request!

**Comment by J-Fo-S** [comment]
Thanks for the reply @jeremymanning . Right now I use the matlab version for different data, but if/when I can merge the two, I'll report what I find. I will tentatively say that tinkering with the regularization parameters seem to help to a degree, but it's only been a few runs. Cheers,
